api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Infrastructure/Doctrine/MealDomain/Entity'
            - '%kernel.project_dir%/src/Infrastructure/Doctrine/UserDomain/Entity'
            - '%kernel.project_dir%/src/MealDomain/Dto'
            - '%kernel.project_dir%/src/UserDomain/Dto'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
