doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '12'
        
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            MealDomain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/MealDomain/Entity'
                prefix: 'App\Entity'
                alias: App
            UserDomain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/UserDomain/Entity'
                prefix: 'App\Entity'
                alias: App
